# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ayeager\PycharmProjects\TradeMaster\DW_FlatRateTask.ui'
#
# Created: Fri Aug 02 21:33:34 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DW_FlatRateTask(object):
    def setupUi(self, DW_FlatRateTask):
        DW_FlatRateTask.setObjectName(_fromUtf8("DW_FlatRateTask"))
        DW_FlatRateTask.resize(1078, 710)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(900, 440, 161, 34))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 480, 161, 34))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 520, 161, 34))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.leditTaskName = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditTaskName.setGeometry(QtCore.QRect(10, 110, 571, 27))
        self.leditTaskName.setObjectName(_fromUtf8("leditTaskName"))
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(880, 0, 21, 391))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(890, 380, 191, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(940, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lblCreateDate = QtGui.QLabel(self.dockWidgetContents)
        self.lblCreateDate.setGeometry(QtCore.QRect(920, 130, 131, 21))
        self.lblCreateDate.setObjectName(_fromUtf8("lblCreateDate"))
        self.lblLastUpdate = QtGui.QLabel(self.dockWidgetContents)
        self.lblLastUpdate.setGeometry(QtCore.QRect(920, 200, 101, 21))
        self.lblLastUpdate.setObjectName(_fromUtf8("lblLastUpdate"))
        self.leditLastUpdate = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditLastUpdate.setGeometry(QtCore.QRect(920, 230, 131, 27))
        self.leditLastUpdate.setObjectName(_fromUtf8("leditLastUpdate"))
        self.leditCreateDate = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditCreateDate.setGeometry(QtCore.QRect(920, 160, 131, 27))
        self.leditCreateDate.setObjectName(_fromUtf8("leditCreateDate"))
        self.lblTaskName = QtGui.QLabel(self.dockWidgetContents)
        self.lblTaskName.setGeometry(QtCore.QRect(10, 80, 271, 21))
        self.lblTaskName.setObjectName(_fromUtf8("lblTaskName"))
        self.lblTaskID = QtGui.QLabel(self.dockWidgetContents)
        self.lblTaskID.setGeometry(QtCore.QRect(920, 60, 101, 21))
        self.lblTaskID.setObjectName(_fromUtf8("lblTaskID"))
        self.leditTaskID = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditTaskID.setGeometry(QtCore.QRect(920, 90, 131, 27))
        self.leditTaskID.setObjectName(_fromUtf8("leditTaskID"))
        self.cboxTaskGroup = QtGui.QComboBox(self.dockWidgetContents)
        self.cboxTaskGroup.setGeometry(QtCore.QRect(610, 110, 261, 27))
        self.cboxTaskGroup.setObjectName(_fromUtf8("cboxTaskGroup"))
        self.lblTaskGroup = QtGui.QLabel(self.dockWidgetContents)
        self.lblTaskGroup.setGeometry(QtCore.QRect(610, 80, 241, 21))
        self.lblTaskGroup.setObjectName(_fromUtf8("lblTaskGroup"))
        self.LblDockTitle = QtGui.QLabel(self.dockWidgetContents)
        self.LblDockTitle.setGeometry(QtCore.QRect(10, 10, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LblDockTitle.setFont(font)
        self.LblDockTitle.setObjectName(_fromUtf8("LblDockTitle"))
        self.lblTaskMaterials = QtGui.QLabel(self.dockWidgetContents)
        self.lblTaskMaterials.setGeometry(QtCore.QRect(10, 370, 191, 21))
        self.lblTaskMaterials.setObjectName(_fromUtf8("lblTaskMaterials"))
        self.leditInvoiceDescription = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditInvoiceDescription.setGeometry(QtCore.QRect(10, 180, 571, 27))
        self.leditInvoiceDescription.setObjectName(_fromUtf8("leditInvoiceDescription"))
        self.lblInvoiceDescription = QtGui.QLabel(self.dockWidgetContents)
        self.lblInvoiceDescription.setGeometry(QtCore.QRect(10, 150, 181, 21))
        self.lblInvoiceDescription.setObjectName(_fromUtf8("lblInvoiceDescription"))
        self.teditDetaildDescription = QtGui.QTextEdit(self.dockWidgetContents)
        self.teditDetaildDescription.setGeometry(QtCore.QRect(10, 250, 571, 107))
        self.teditDetaildDescription.setObjectName(_fromUtf8("teditDetaildDescription"))
        self.lblDetailedDescription = QtGui.QLabel(self.dockWidgetContents)
        self.lblDetailedDescription.setGeometry(QtCore.QRect(10, 220, 321, 21))
        self.lblDetailedDescription.setObjectName(_fromUtf8("lblDetailedDescription"))
        self.tblviewTaskMaterials = QtGui.QTableView(self.dockWidgetContents)
        self.tblviewTaskMaterials.setGeometry(QtCore.QRect(10, 400, 871, 201))
        self.tblviewTaskMaterials.setObjectName(_fromUtf8("tblviewTaskMaterials"))
        self.leditMaterialHours = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditMaterialHours.setGeometry(QtCore.QRect(720, 270, 151, 27))
        self.leditMaterialHours.setText(_fromUtf8(""))
        self.leditMaterialHours.setObjectName(_fromUtf8("leditMaterialHours"))
        self.lblMaterialHrs = QtGui.QLabel(self.dockWidgetContents)
        self.lblMaterialHrs.setGeometry(QtCore.QRect(720, 240, 151, 21))
        self.lblMaterialHrs.setObjectName(_fromUtf8("lblMaterialHrs"))
        self.leditBillHours = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditBillHours.setGeometry(QtCore.QRect(720, 190, 151, 27))
        self.leditBillHours.setText(_fromUtf8(""))
        self.leditBillHours.setObjectName(_fromUtf8("leditBillHours"))
        self.lblBillHours = QtGui.QLabel(self.dockWidgetContents)
        self.lblBillHours.setGeometry(QtCore.QRect(720, 160, 151, 21))
        self.lblBillHours.setObjectName(_fromUtf8("lblBillHours"))
        self.label_13 = QtGui.QLabel(self.dockWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(920, 290, 131, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.leditAvgComplete = QtGui.QLineEdit(self.dockWidgetContents)
        self.leditAvgComplete.setGeometry(QtCore.QRect(910, 350, 151, 27))
        self.leditAvgComplete.setText(_fromUtf8(""))
        self.leditAvgComplete.setObjectName(_fromUtf8("leditAvgComplete"))
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(940, 320, 91, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.line_3 = QtGui.QFrame(self.dockWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(0, 610, 1081, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.buttonBox = QtGui.QDialogButtonBox(self.dockWidgetContents)
        self.buttonBox.setGeometry(QtCore.QRect(552, 630, 511, 34))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        DW_FlatRateTask.setWidget(self.dockWidgetContents)

        self.retranslateUi(DW_FlatRateTask)
        QtCore.QMetaObject.connectSlotsByName(DW_FlatRateTask)

    def retranslateUi(self, DW_FlatRateTask):
        DW_FlatRateTask.setWindowTitle(_translate("DW_FlatRateTask", "DockWidget", None))
        self.pushButton.setText(_translate("DW_FlatRateTask", "Add", None))
        self.pushButton_2.setText(_translate("DW_FlatRateTask", "Remove", None))
        self.pushButton_3.setText(_translate("DW_FlatRateTask", "Edit", None))
        self.label.setText(_translate("DW_FlatRateTask", "Task Info", None))
        self.lblCreateDate.setText(_translate("DW_FlatRateTask", "Creation Date", None))
        self.lblLastUpdate.setText(_translate("DW_FlatRateTask", "Last Updated", None))
        self.lblTaskName.setText(_translate("DW_FlatRateTask", "Task Name", None))
        self.lblTaskID.setText(_translate("DW_FlatRateTask", "Task ID", None))
        self.lblTaskGroup.setText(_translate("DW_FlatRateTask", "Task Group", None))
        self.LblDockTitle.setText(_translate("DW_FlatRateTask", "Flat Rate Task", None))
        self.lblTaskMaterials.setText(_translate("DW_FlatRateTask", "Task Materials:", None))
        self.lblInvoiceDescription.setText(_translate("DW_FlatRateTask", "Invoice Description", None))
        self.lblDetailedDescription.setText(_translate("DW_FlatRateTask", "Detailed Description", None))
        self.lblMaterialHrs.setText(_translate("DW_FlatRateTask", "Material Labor Hrs.", None))
        self.lblBillHours.setText(_translate("DW_FlatRateTask", "Labor Hours to Bill", None))
        self.label_13.setText(_translate("DW_FlatRateTask", "Avg. Labor Hours", None))
        self.label_14.setText(_translate("DW_FlatRateTask", "to complete", None))

