# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ayeager\PycharmProjects\TradeMaster\EmployeeDetails_DW.ui'
#
# Created: Fri Aug 02 21:33:36 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(1137, 772)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TabsEmployeeDetails = QtGui.QTabWidget(self.dockWidgetContents)
        self.TabsEmployeeDetails.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TabsEmployeeDetails.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.TabsEmployeeDetails.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.TabsEmployeeDetails.setTabPosition(QtGui.QTabWidget.North)
        self.TabsEmployeeDetails.setTabShape(QtGui.QTabWidget.Rounded)
        self.TabsEmployeeDetails.setDocumentMode(False)
        self.TabsEmployeeDetails.setTabsClosable(False)
        self.TabsEmployeeDetails.setMovable(False)
        self.TabsEmployeeDetails.setObjectName(_fromUtf8("TabsEmployeeDetails"))
        self.TabEmpGeneral = QtGui.QWidget()
        self.TabEmpGeneral.setObjectName(_fromUtf8("TabEmpGeneral"))
        self.EmpFirstName = QtGui.QLineEdit(self.TabEmpGeneral)
        self.EmpFirstName.setGeometry(QtCore.QRect(40, 70, 176, 27))
        self.EmpFirstName.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EmpFirstName.setObjectName(_fromUtf8("EmpFirstName"))
        self.LblEmpFirstName = QtGui.QLabel(self.TabEmpGeneral)
        self.LblEmpFirstName.setGeometry(QtCore.QRect(40, 40, 176, 21))
        self.LblEmpFirstName.setObjectName(_fromUtf8("LblEmpFirstName"))
        self.EmpMiddleName = QtGui.QLineEdit(self.TabEmpGeneral)
        self.EmpMiddleName.setGeometry(QtCore.QRect(240, 70, 176, 27))
        self.EmpMiddleName.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EmpMiddleName.setText(_fromUtf8(""))
        self.EmpMiddleName.setObjectName(_fromUtf8("EmpMiddleName"))
        self.LblEmpMiddleName = QtGui.QLabel(self.TabEmpGeneral)
        self.LblEmpMiddleName.setGeometry(QtCore.QRect(240, 40, 176, 21))
        self.LblEmpMiddleName.setObjectName(_fromUtf8("LblEmpMiddleName"))
        self.EmpLastName = QtGui.QLineEdit(self.TabEmpGeneral)
        self.EmpLastName.setGeometry(QtCore.QRect(440, 70, 176, 27))
        self.EmpLastName.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EmpLastName.setObjectName(_fromUtf8("EmpLastName"))
        self.LblEmpLastName = QtGui.QLabel(self.TabEmpGeneral)
        self.LblEmpLastName.setGeometry(QtCore.QRect(440, 40, 176, 21))
        self.LblEmpLastName.setObjectName(_fromUtf8("LblEmpLastName"))
        self.EmpPhoto = QtGui.QGraphicsView(self.TabEmpGeneral)
        self.EmpPhoto.setGeometry(QtCore.QRect(40, 120, 371, 391))
        self.EmpPhoto.setObjectName(_fromUtf8("EmpPhoto"))
        self.TabsEmployeeDetails.addTab(self.TabEmpGeneral, _fromUtf8(""))
        self.TabEmpPersonalInfo = QtGui.QWidget()
        self.TabEmpPersonalInfo.setObjectName(_fromUtf8("TabEmpPersonalInfo"))
        self.groupPhysAddress = QtGui.QGroupBox(self.TabEmpPersonalInfo)
        self.groupPhysAddress.setGeometry(QtCore.QRect(20, 40, 431, 161))
        self.groupPhysAddress.setObjectName(_fromUtf8("groupPhysAddress"))
        self.phyAddress1 = QtGui.QLineEdit(self.groupPhysAddress)
        self.phyAddress1.setGeometry(QtCore.QRect(10, 30, 391, 27))
        self.phyAddress1.setObjectName(_fromUtf8("phyAddress1"))
        self.phyAddress2 = QtGui.QLineEdit(self.groupPhysAddress)
        self.phyAddress2.setGeometry(QtCore.QRect(10, 70, 391, 27))
        self.phyAddress2.setText(_fromUtf8(""))
        self.phyAddress2.setObjectName(_fromUtf8("phyAddress2"))
        self.phyCity = QtGui.QLineEdit(self.groupPhysAddress)
        self.phyCity.setGeometry(QtCore.QRect(10, 110, 171, 27))
        self.phyCity.setObjectName(_fromUtf8("phyCity"))
        self.phyState = QtGui.QComboBox(self.groupPhysAddress)
        self.phyState.setGeometry(QtCore.QRect(200, 110, 71, 27))
        self.phyState.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.phyState.setObjectName(_fromUtf8("phyState"))
        self.phyState.addItem(_fromUtf8(""))
        self.phyState.addItem(_fromUtf8(""))
        self.phyZipcode = QtGui.QLineEdit(self.groupPhysAddress)
        self.phyZipcode.setGeometry(QtCore.QRect(290, 110, 111, 27))
        self.phyZipcode.setObjectName(_fromUtf8("phyZipcode"))
        self.groupMailAddress = QtGui.QGroupBox(self.TabEmpPersonalInfo)
        self.groupMailAddress.setGeometry(QtCore.QRect(20, 210, 431, 161))
        self.groupMailAddress.setObjectName(_fromUtf8("groupMailAddress"))
        self.mailAddress1 = QtGui.QLineEdit(self.groupMailAddress)
        self.mailAddress1.setGeometry(QtCore.QRect(10, 30, 391, 27))
        self.mailAddress1.setObjectName(_fromUtf8("mailAddress1"))
        self.mailAddress2 = QtGui.QLineEdit(self.groupMailAddress)
        self.mailAddress2.setGeometry(QtCore.QRect(10, 70, 391, 27))
        self.mailAddress2.setObjectName(_fromUtf8("mailAddress2"))
        self.mailCity = QtGui.QLineEdit(self.groupMailAddress)
        self.mailCity.setGeometry(QtCore.QRect(10, 110, 171, 27))
        self.mailCity.setObjectName(_fromUtf8("mailCity"))
        self.mailState = QtGui.QComboBox(self.groupMailAddress)
        self.mailState.setGeometry(QtCore.QRect(200, 110, 71, 27))
        self.mailState.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.mailState.setObjectName(_fromUtf8("mailState"))
        self.mailState.addItem(_fromUtf8(""))
        self.mailState.addItem(_fromUtf8(""))
        self.mailZip = QtGui.QLineEdit(self.groupMailAddress)
        self.mailZip.setGeometry(QtCore.QRect(290, 110, 111, 27))
        self.mailZip.setObjectName(_fromUtf8("mailZip"))
        self.CboxSameAddress = QtGui.QCheckBox(self.groupMailAddress)
        self.CboxSameAddress.setGeometry(QtCore.QRect(150, 0, 161, 25))
        self.CboxSameAddress.setObjectName(_fromUtf8("CboxSameAddress"))
        self.groupPhone = QtGui.QGroupBox(self.TabEmpPersonalInfo)
        self.groupPhone.setGeometry(QtCore.QRect(20, 380, 431, 171))
        self.groupPhone.setObjectName(_fromUtf8("groupPhone"))
        self.homePhone = QtGui.QLineEdit(self.groupPhone)
        self.homePhone.setGeometry(QtCore.QRect(20, 60, 131, 27))
        self.homePhone.setObjectName(_fromUtf8("homePhone"))
        self.label = QtGui.QLabel(self.groupPhone)
        self.label.setGeometry(QtCore.QRect(20, 30, 70, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.cellPhone = QtGui.QLineEdit(self.groupPhone)
        self.cellPhone.setGeometry(QtCore.QRect(20, 130, 131, 27))
        self.cellPhone.setText(_fromUtf8(""))
        self.cellPhone.setObjectName(_fromUtf8("cellPhone"))
        self.label_2 = QtGui.QLabel(self.groupPhone)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 70, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.workPhone = QtGui.QLineEdit(self.groupPhone)
        self.workPhone.setGeometry(QtCore.QRect(190, 60, 131, 27))
        self.workPhone.setText(_fromUtf8(""))
        self.workPhone.setObjectName(_fromUtf8("workPhone"))
        self.label_3 = QtGui.QLabel(self.groupPhone)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 70, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.workExtension = QtGui.QLineEdit(self.groupPhone)
        self.workExtension.setGeometry(QtCore.QRect(330, 60, 81, 27))
        self.workExtension.setObjectName(_fromUtf8("workExtension"))
        self.groupEmail = QtGui.QGroupBox(self.TabEmpPersonalInfo)
        self.groupEmail.setGeometry(QtCore.QRect(460, 390, 601, 101))
        self.groupEmail.setObjectName(_fromUtf8("groupEmail"))
        self.workEmail = QtGui.QLineEdit(self.groupEmail)
        self.workEmail.setGeometry(QtCore.QRect(10, 60, 261, 27))
        self.workEmail.setObjectName(_fromUtf8("workEmail"))
        self.personalEmail = QtGui.QLineEdit(self.groupEmail)
        self.personalEmail.setGeometry(QtCore.QRect(290, 60, 301, 27))
        self.personalEmail.setObjectName(_fromUtf8("personalEmail"))
        self.label_4 = QtGui.QLabel(self.groupEmail)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 70, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupEmail)
        self.label_5.setGeometry(QtCore.QRect(290, 30, 70, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupEmergencyContacts = QtGui.QGroupBox(self.TabEmpPersonalInfo)
        self.groupEmergencyContacts.setGeometry(QtCore.QRect(460, 50, 601, 331))
        self.groupEmergencyContacts.setObjectName(_fromUtf8("groupEmergencyContacts"))
        self.groupPrimaryEC = QtGui.QGroupBox(self.groupEmergencyContacts)
        self.groupPrimaryEC.setGeometry(QtCore.QRect(10, 30, 581, 151))
        self.groupPrimaryEC.setObjectName(_fromUtf8("groupPrimaryEC"))
        self.namePEC = QtGui.QLineEdit(self.groupPrimaryEC)
        self.namePEC.setGeometry(QtCore.QRect(20, 40, 291, 27))
        self.namePEC.setObjectName(_fromUtf8("namePEC"))
        self.homePhonePEC = QtGui.QLineEdit(self.groupPrimaryEC)
        self.homePhonePEC.setGeometry(QtCore.QRect(20, 110, 131, 27))
        self.homePhonePEC.setObjectName(_fromUtf8("homePhonePEC"))
        self.label_6 = QtGui.QLabel(self.groupPrimaryEC)
        self.label_6.setGeometry(QtCore.QRect(190, 80, 70, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.workPhonePEC = QtGui.QLineEdit(self.groupPrimaryEC)
        self.workPhonePEC.setGeometry(QtCore.QRect(190, 110, 131, 27))
        self.workPhonePEC.setText(_fromUtf8(""))
        self.workPhonePEC.setObjectName(_fromUtf8("workPhonePEC"))
        self.label_7 = QtGui.QLabel(self.groupPrimaryEC)
        self.label_7.setGeometry(QtCore.QRect(440, 80, 70, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cellPhonePEC = QtGui.QLineEdit(self.groupPrimaryEC)
        self.cellPhonePEC.setGeometry(QtCore.QRect(440, 110, 131, 27))
        self.cellPhonePEC.setText(_fromUtf8(""))
        self.cellPhonePEC.setObjectName(_fromUtf8("cellPhonePEC"))
        self.label_8 = QtGui.QLabel(self.groupPrimaryEC)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 70, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.workExtensionPEC = QtGui.QLineEdit(self.groupPrimaryEC)
        self.workExtensionPEC.setGeometry(QtCore.QRect(330, 110, 81, 27))
        self.workExtensionPEC.setObjectName(_fromUtf8("workExtensionPEC"))
        self.relationshipPEC = QtGui.QComboBox(self.groupPrimaryEC)
        self.relationshipPEC.setGeometry(QtCore.QRect(330, 40, 241, 27))
        self.relationshipPEC.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.relationshipPEC.setMinimumContentsLength(0)
        self.relationshipPEC.setObjectName(_fromUtf8("relationshipPEC"))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.relationshipPEC.addItem(_fromUtf8(""))
        self.groupSecondaryEC = QtGui.QGroupBox(self.groupEmergencyContacts)
        self.groupSecondaryEC.setGeometry(QtCore.QRect(10, 180, 581, 141))
        self.groupSecondaryEC.setObjectName(_fromUtf8("groupSecondaryEC"))
        self.label_9 = QtGui.QLabel(self.groupSecondaryEC)
        self.label_9.setGeometry(QtCore.QRect(190, 70, 70, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.nameSEC = QtGui.QLineEdit(self.groupSecondaryEC)
        self.nameSEC.setGeometry(QtCore.QRect(20, 30, 291, 27))
        self.nameSEC.setObjectName(_fromUtf8("nameSEC"))
        self.realtionshipSEC = QtGui.QComboBox(self.groupSecondaryEC)
        self.realtionshipSEC.setGeometry(QtCore.QRect(330, 30, 241, 27))
        self.realtionshipSEC.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.realtionshipSEC.setObjectName(_fromUtf8("realtionshipSEC"))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.realtionshipSEC.addItem(_fromUtf8(""))
        self.homePhoneSEC = QtGui.QLineEdit(self.groupSecondaryEC)
        self.homePhoneSEC.setGeometry(QtCore.QRect(20, 100, 131, 27))
        self.homePhoneSEC.setObjectName(_fromUtf8("homePhoneSEC"))
        self.label_10 = QtGui.QLabel(self.groupSecondaryEC)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 70, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.workPhoneSEC = QtGui.QLineEdit(self.groupSecondaryEC)
        self.workPhoneSEC.setGeometry(QtCore.QRect(190, 100, 131, 27))
        self.workPhoneSEC.setText(_fromUtf8(""))
        self.workPhoneSEC.setObjectName(_fromUtf8("workPhoneSEC"))
        self.label_11 = QtGui.QLabel(self.groupSecondaryEC)
        self.label_11.setGeometry(QtCore.QRect(440, 70, 70, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cellPhoneSEC = QtGui.QLineEdit(self.groupSecondaryEC)
        self.cellPhoneSEC.setGeometry(QtCore.QRect(440, 100, 131, 27))
        self.cellPhoneSEC.setText(_fromUtf8(""))
        self.cellPhoneSEC.setObjectName(_fromUtf8("cellPhoneSEC"))
        self.workExtensionSEC = QtGui.QLineEdit(self.groupSecondaryEC)
        self.workExtensionSEC.setGeometry(QtCore.QRect(330, 100, 81, 27))
        self.workExtensionSEC.setObjectName(_fromUtf8("workExtensionSEC"))
        self.TabsEmployeeDetails.addTab(self.TabEmpPersonalInfo, _fromUtf8(""))
        self.TabEmpEmploymentInfo = QtGui.QWidget()
        self.TabEmpEmploymentInfo.setObjectName(_fromUtf8("TabEmpEmploymentInfo"))
        self.groupBox_5 = QtGui.QGroupBox(self.TabEmpEmploymentInfo)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 560, 401, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 171, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 70, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox_5)
        self.dateEdit.setGeometry(QtCore.QRect(280, 20, 111, 27))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.comboBox = QtGui.QComboBox(self.groupBox_5)
        self.comboBox.setGeometry(QtCore.QRect(280, 60, 111, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(200, 30, 70, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(200, 70, 70, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.TabsEmployeeDetails.addTab(self.TabEmpEmploymentInfo, _fromUtf8(""))
        self.TabEmpLiscenseCerts = QtGui.QWidget()
        self.TabEmpLiscenseCerts.setObjectName(_fromUtf8("TabEmpLiscenseCerts"))
        self.TabsEmployeeDetails.addTab(self.TabEmpLiscenseCerts, _fromUtf8(""))
        self.gridLayout.addWidget(self.TabsEmployeeDetails, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.TabsEmployeeDetails.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.phyAddress1, self.phyAddress2)
        DockWidget.setTabOrder(self.phyAddress2, self.phyCity)
        DockWidget.setTabOrder(self.phyCity, self.phyState)
        DockWidget.setTabOrder(self.phyState, self.phyZipcode)
        DockWidget.setTabOrder(self.phyZipcode, self.CboxSameAddress)
        DockWidget.setTabOrder(self.CboxSameAddress, self.mailAddress1)
        DockWidget.setTabOrder(self.mailAddress1, self.mailAddress2)
        DockWidget.setTabOrder(self.mailAddress2, self.mailCity)
        DockWidget.setTabOrder(self.mailCity, self.mailState)
        DockWidget.setTabOrder(self.mailState, self.mailZip)
        DockWidget.setTabOrder(self.mailZip, self.homePhone)
        DockWidget.setTabOrder(self.homePhone, self.workPhone)
        DockWidget.setTabOrder(self.workPhone, self.workExtension)
        DockWidget.setTabOrder(self.workExtension, self.cellPhone)
        DockWidget.setTabOrder(self.cellPhone, self.workEmail)
        DockWidget.setTabOrder(self.workEmail, self.personalEmail)
        DockWidget.setTabOrder(self.personalEmail, self.EmpMiddleName)
        DockWidget.setTabOrder(self.EmpMiddleName, self.EmpPhoto)
        DockWidget.setTabOrder(self.EmpPhoto, self.EmpFirstName)
        DockWidget.setTabOrder(self.EmpFirstName, self.EmpLastName)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.LblEmpFirstName.setText(_translate("DockWidget", "First Name", None))
        self.LblEmpMiddleName.setText(_translate("DockWidget", "Middle Name", None))
        self.LblEmpLastName.setText(_translate("DockWidget", "Last Name", None))
        self.TabsEmployeeDetails.setTabText(self.TabsEmployeeDetails.indexOf(self.TabEmpGeneral), _translate("DockWidget", "General", None))
        self.groupPhysAddress.setTitle(_translate("DockWidget", "Physical Address", None))
        self.phyAddress1.setPlaceholderText(_translate("DockWidget", "Street Address", None))
        self.phyAddress2.setPlaceholderText(_translate("DockWidget", "Address 2 (Suite, Apt, etc....)", None))
        self.phyCity.setPlaceholderText(_translate("DockWidget", "City", None))
        self.phyState.setItemText(0, _translate("DockWidget", "TX", None))
        self.phyState.setItemText(1, _translate("DockWidget", "MN", None))
        self.phyZipcode.setPlaceholderText(_translate("DockWidget", "Zipcode", None))
        self.groupMailAddress.setTitle(_translate("DockWidget", "Mailing Address", None))
        self.mailAddress1.setPlaceholderText(_translate("DockWidget", "Street Address or PO Box", None))
        self.mailAddress2.setPlaceholderText(_translate("DockWidget", "Address 2 (Suite, Apt, etc....)", None))
        self.mailCity.setPlaceholderText(_translate("DockWidget", "City", None))
        self.mailState.setItemText(0, _translate("DockWidget", "TX", None))
        self.mailState.setItemText(1, _translate("DockWidget", "MN", None))
        self.mailZip.setPlaceholderText(_translate("DockWidget", "Zipcode", None))
        self.CboxSameAddress.setText(_translate("DockWidget", "Same as Physical", None))
        self.groupPhone.setTitle(_translate("DockWidget", "Phone Info", None))
        self.homePhone.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label.setText(_translate("DockWidget", "Home", None))
        self.cellPhone.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_2.setText(_translate("DockWidget", "Mobile", None))
        self.workPhone.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_3.setText(_translate("DockWidget", "Work", None))
        self.workExtension.setPlaceholderText(_translate("DockWidget", "Extension", None))
        self.groupEmail.setTitle(_translate("DockWidget", "Email", None))
        self.label_4.setText(_translate("DockWidget", "Work ", None))
        self.label_5.setText(_translate("DockWidget", "Personal", None))
        self.groupEmergencyContacts.setTitle(_translate("DockWidget", "Emergency Contacts", None))
        self.groupPrimaryEC.setTitle(_translate("DockWidget", "Primary", None))
        self.namePEC.setPlaceholderText(_translate("DockWidget", "Name", None))
        self.homePhonePEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_6.setText(_translate("DockWidget", "Work", None))
        self.workPhonePEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_7.setText(_translate("DockWidget", "Mobile", None))
        self.cellPhonePEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_8.setText(_translate("DockWidget", "Home", None))
        self.workExtensionPEC.setPlaceholderText(_translate("DockWidget", "Extension", None))
        self.relationshipPEC.setItemText(0, _translate("DockWidget", "Spouse", None))
        self.relationshipPEC.setItemText(1, _translate("DockWidget", "Parent", None))
        self.relationshipPEC.setItemText(2, _translate("DockWidget", "Sibling", None))
        self.relationshipPEC.setItemText(3, _translate("DockWidget", "Child", None))
        self.relationshipPEC.setItemText(4, _translate("DockWidget", "Friend", None))
        self.relationshipPEC.setItemText(5, _translate("DockWidget", "Other", None))
        self.groupSecondaryEC.setTitle(_translate("DockWidget", "Secondary", None))
        self.label_9.setText(_translate("DockWidget", "Work", None))
        self.nameSEC.setPlaceholderText(_translate("DockWidget", "Name", None))
        self.realtionshipSEC.setItemText(0, _translate("DockWidget", "Spouse", None))
        self.realtionshipSEC.setItemText(1, _translate("DockWidget", "Parent", None))
        self.realtionshipSEC.setItemText(2, _translate("DockWidget", "Sibling", None))
        self.realtionshipSEC.setItemText(3, _translate("DockWidget", "Child", None))
        self.realtionshipSEC.setItemText(4, _translate("DockWidget", "Friend", None))
        self.realtionshipSEC.setItemText(5, _translate("DockWidget", "Other", None))
        self.homePhoneSEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_10.setText(_translate("DockWidget", "Home", None))
        self.workPhoneSEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.label_11.setText(_translate("DockWidget", "Mobile", None))
        self.cellPhoneSEC.setPlaceholderText(_translate("DockWidget", "(xxx) xxx-xxxx", None))
        self.workExtensionSEC.setPlaceholderText(_translate("DockWidget", "Extension", None))
        self.TabsEmployeeDetails.setTabText(self.TabsEmployeeDetails.indexOf(self.TabEmpPersonalInfo), _translate("DockWidget", "Personal", None))
        self.groupBox_5.setTitle(_translate("DockWidget", "Personal Data", None))
        self.lineEdit.setPlaceholderText(_translate("DockWidget", "xxx-xx-xxxx", None))
        self.label_12.setText(_translate("DockWidget", "SSN", None))
        self.comboBox.setItemText(0, _translate("DockWidget", "Male", None))
        self.comboBox.setItemText(1, _translate("DockWidget", "Female", None))
        self.label_13.setText(_translate("DockWidget", "Birthdate", None))
        self.label_14.setText(_translate("DockWidget", "Gender", None))
        self.TabsEmployeeDetails.setTabText(self.TabsEmployeeDetails.indexOf(self.TabEmpEmploymentInfo), _translate("DockWidget", "Employment", None))
        self.TabsEmployeeDetails.setTabText(self.TabsEmployeeDetails.indexOf(self.TabEmpLiscenseCerts), _translate("DockWidget", "Liscense && Certs", None))

